### ISSUE TITLE
Configuration 'compile' in project ':barcode_scan' is deprecated. Use 'implementation' instead.

### ISSUE THREAD

**Issue by ctrleffive** [iampawan/FlutterQRScanner-App#1]
This warning is showing up during the debug time.

`Configuration 'compile' in project ':barcode_scan' is deprecated. Use 'implementation' instead.`

**Comment by iampawan** [comment]
Not an issue. It's about the latest Gradle changes which need to be done by the developer of the barcode scan library. So, it will be fixed before it gets obsolete.
