### ISSUE TITLE
Program type already present: android.arch.core.util.Function

### ISSUE THREAD

**Issue by cbyniiaii** [iampawan/FlutterQRScanner-App#2]
pubspec.yaml

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:
  intl_translation:
  firebase_auth:
  google_sign_in:
  cloud_firestore:
  firebase_analytics:
  barcode_scan:
  cupertino_icons: ^0.1.2

**Comment by Timoteohss** [comment]
The same is happening on my end.

**Comment by iampawan** [comment]
I have updated the code and your issue might be happening because of some other plugin.
