### ISSUE TITLE
How to set the box to scan the QR code to a square

### ISSUE THREAD

**Issue by zzZ-F** [iampawan/FlutterQRScanner-App#3]
How to set the box to scan the QR code to a square?  

The QR code scanning frame is usually square but not rectangular.  
Thank you

**Comment by zzZ-F** [comment]
Whether the Android back button can still exist, so the style is neat

**Comment by iampawan** [comment]
This is just a demo of the plugin which I am using so not a good place to raise this issue. Closing for now.
