### ISSUE TITLE
Build error after adding cloud_firestore to the project

### ISSUE THREAD

**Issue by sushi999** [iampawan/FlutterQRScanner-App#4]
Getting the following error 

Execution failed for task ':app:preDebugBuild'.
> Android dependency 'androidx.core:core' has different version for the compile (1.0.0) and runtime (1.0.1) classpath. You should manually set the same version via DependencyResolution

**Comment by iandreyshev** [comment]
@sushi999 have the same problem

**Comment by iampawan** [comment]
I have updated the code and your issue might be happening because of cloud firestore. So not relevant to this repo. Hence closing it for now
